colin/urls.py
from django.conf.urls import include, url, static
from django.contrib import admin
from django.conf import settings


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('colin_dot_com.urls')),
] + static.static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

colin_dot_com/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^products/$', views.list, name='list'),
    url(r'^$', views.index, name='index'),
    url(r'^products/(?P<product_id>[0-9]+)/$', views.show, name='show'),
    url(r'^products/add/$', views.add, name='add'),
    url(r'^products/(?P<product_url>.+)/$', views.show, name='show'),
    url(r'^companies/$', views.list_companies, name='list_companies'),
    url(r'^companies/(?P<company_id>[0-9]+)/$', views.show_company, name='show_company')
]

colin_dot_com/models.py
from django.db import models

import datetime
from django.utils import timezone

class MaterialTag(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

class Material(models.Model):
    name = models.CharField(max_length=200)
    tags = models.ManyToManyField(MaterialTag, blank=True)

    def __str__(self):
        return self.name

class Color(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

class ShortSize(models.Model):
    name = models.CharField(max_length=6)

    def __str__(self):
        return self.name

class Product(models.Model):
    name = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date_published")
    description = models.TextField(default="")
    material = models.ForeignKey(Material, null=True)
    color = models.ForeignKey(Color, null=True)
    price = models.DecimalField(max_digits=6, decimal_places=2, default='0000.00')
    short_size = models.ForeignKey(ShortSize, null=True)
    image = models.ImageField(null=True)
    short_url = models.CharField(max_length=200, null=True, unique=True)

class Company(models.Model):
    name = models.CharField(max_length=200)
    date_added = models.DateTimeField("date_added")
    blurb = models.CharField(max_length=250, default="")
    address_line_1 = models.CharField(max_length=1000, default="")
    address_line_2 = models.CharField(max_length=1000, default="")
    logo = models.ImageField(null=True)

    def __str__(self):
        return self.name

class Project(models.Model):
    name = models.CharField(max_length=200)
    date_added = models.DateTimeField()
    company = models.ForeignKey(Company, null=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

class Photo(models.Model):
    name = models.CharField(max_length=200)
    date_added = models.DateTimeField()
    image = models.ImageField(null=False)
    caption = models.CharField(max_length=250, null=True)
    project = models.ForeignKey(Project, null=True, on_delete=models.CASCADE)
    # todo: tags on photos

    def __str__(self):
        return self.name








# Create your models here.

colin_dot_com/forms.py
from django.forms import ModelForm
from .models import Product

class ProductForm(ModelForm):
    class Meta:
        model = Product
        fields = [
            'name',
            'description',
            'price',
            'material',
            'color',
            'short_size',
            'image'
        ]

colin_dot_com/views.py
# Create your views here.

import logging
import datetime

from django.core import serializers
from django.http import HttpResponse, Http404, JsonResponse, HttpResponseRedirect, HttpResponseServerError
from django.template import loader, RequestContext
from django.shortcuts import render

from colin_dot_com.models import Product, ShortSize, Color, Material, Company, Photo, Project
from colin_dot_com.forms import ProductForm

logger = logging.getLogger("colin")

def index(request):
    return HttpResponseRedirect("/products/")

def list_companies(request):
    companies = Company.objects.order_by("-date_added")[:100]
    template = loader.get_template('colin_dot_com/company_list.html')
    context = {
        'companies' : companies,
    }
    return HttpResponse(template.render(context, request))

def show_company(request, company_id=None):
    logger.debug("user " + request.user.username.__str__())
    if (company_id is not None):
        company = Company.objects.get(pk=company_id)
    else:
        raise Http404("Company not found.")

    template = loader.get_template('colin_dot_com/show_company.html')
    context = RequestContext(request, {
        'company' : company,
    })
    return HttpResponse(template.render(context, request))

def list(request):
    products = Product.objects.order_by('-pub_date')[:100]
    template = loader.get_template('colin_dot_com/list.html')
    context = {
        'products': products,
    }
    return HttpResponse(template.render(context, request))

def show(request, product_id=None, product_url=None):
    try:
        if (product_id is not None):
            product = Product.objects.get(pk=product_id)
        elif (product_url is not None):
            product = Product.objects.get(short_url=product_url)
        else:
            raise Http404("Product not found.")
    except:
        raise Http404("Product not found.")
    template = loader.get_template('colin_dot_com/show.html')
    context = RequestContext(request,  {
        'product' : product
    })
    format = request.GET.get('format')
    if (format == 'json'):
        return JsonResponse(serializers.serialize('json', [product]), safe=False)
    return HttpResponse(template.render(context, request))

def add(request):
    if (request.method == 'GET'):
        template = loader.get_template('colin_dot_com/add.html')
        # sizes = ShortSize.objects.all()
        # colors = Color.objects.all()
        # materials = Material.objects.all()
        # context = RequestContext(request, {
        #     'sizes' : sizes,
        #     'colors' : colors,
        #     'materials' : materials
        # })
        form = ProductForm(request.POST)
        return render(request, 'colin_dot_com/add2.html', {'form': form})
    if (request.method == 'POST'):
        logger.debug(request.POST.get("name"))

        form = ProductForm(request.POST)

        if form.is_valid():
            form.save()



        # product = Product(
        #     name=request.POST['name'],
        #     description=request.POST['description'],
        #     pub_date=datetime.datetime.now(),
        #     color=Color.objects.get(name=request.POST['color']),
        #     short_size=ShortSize.objects.get(name=request.POST['size']),
        #     material=Material.objects.get(name=request.POST['material']),
        #     price=float(request.POST['price']),
        #     image=request.POST['image'],
        # )
        # for upfile in request.FILES.getlist('image'):
        #     filename = upfile.name
        #     fd = open(filename, 'w+')
        #     for chunk in upfile.chunks:
        #         fd.write(chunk)
        #     fd.close()
        # product.save()
        return HttpResponseRedirect("/products/")

colin_dot_com/templates/colin_dot_com/add.html
{% extends "colin_dot_com/bauble_dot_com.html" %}

{% block navigation %}
    <ul class="breadcrumbs">
      <li><a href="/">home</a></li>
      <li><a href="/products">products</a> </li>
      <li><a class="current" href="/products/add">add</a></li>
    </ul>
{% endblock %}

{% block content %}
    <form action="/products/add/" method="post" enctype="multipart/form-data">
        <label>name<input type="text" placeholder="Name" name="name"></label>
        <label>description
            <textarea placeholder="Describe your product. Let people know what makes it special." name="description"></textarea>
        </label>
        <label>image
            <input type="file" name="image">
        </label>
        <label>price
            <input type="number" placeholder="Price" name="price">
        </label>
        </label>
        <label>size
            <select name="size">
                {% for size in sizes %}
                    <option value="{{ size.name }}">{{ size.name }}</option>
                {% endfor %}
            </select>
        </label>
        <label>color
            <select class="color" name="color">
                {% for color in colors %}
                    <option value="{{ color.name }}">{{ color.name }}</option>
                {% endfor %}
            </select>
        </label>
        <label>material
            <select class="material" name="material">
                {% for material in materials %}
                    <option value="{{ material.name }}">{{ material.name }}</option>
                {% endfor %}
            </select>
        </label>
        <input type="submit" value="add">
        {% csrf_token %}
    </form>
{% endblock %}

colin_dot_com/templates/colin_dot_com/add2.html
{% extends "colin_dot_com/bauble_dot_com.html" %}

{% block navigation %}
    <ul class="breadcrumbs">
      <li><a href="/">home</a></li>
      <li><a href="/products">products</a> </li>
      <li><a class="current" href="/products/add">add</a></li>
    </ul>
{% endblock %}

{% block content %}
    <form action="/products/add/" method="post" enctype="multipart/form-data">
        {{ form.as_p }}
        <input type="submit" value="add">
        {% csrf_token %}
    </form>
    <script>
        $(document).ready(function() {
            $("ul.errorlist").each(function (index) {
                $(this).appendTo($(this).parent());
            });
        });
    </script>

});
{% endblock %}

colin_dot_com/templates/colin_dot_com/bauble_dot_com.html
<!DOCTYPE html>

{% load staticfiles %}

<html>
    <head>
        <title>bauble</title>
        <link type="text/css" rel="stylesheet" href="{% static 'colin_dot_com/foundation.min.css' %}">
        <link type="text/css" rel="stylesheet" href="{% static 'colin_dot_com/base.css' %}">
        <link href='https://fonts.googleapis.com/css?family=Playfair+Display:400,400italic,700,700italic' rel='stylesheet' type='text/css'>

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
        <script src="{% static 'colin_dot_com/selectize.min.js' %}"></script>
    </head>
    <body>
        <div class="row">
            <div class="small-12 large-8 small-centered columns">
                <h1>bauble</h1>
                <div id="nav">{% block navigation %}{% endblock %}</div>
            </div>
        </div>
        <div class="row">
            <div class="small-12 large-8 small-centered columns">
                {% block content %} {% endblock %}
            </div>
        </div>
    </body>
</html>

colin_dot_com/templates/colin_dot_com/colin_dot_com.html
<!DOCTYPE html>

{% load staticfiles %}

<html>
    <head>
        <title>colin</title>
        <link type="text/css" rel="stylesheet" href="{% static 'colin_dot_com/foundation.min.css' %}">
        <link type="text/css" rel="stylesheet" href="{% static 'colin_dot_com/base.css' %}">
        <link href='https://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
        <script src="{% static 'colin_dot_com/foundation.min.js' %}"></script>
        <script src="{% static 'colin_dot_com/selectize.min.js' %}"></script>
    </head>
    <body>
        <div class="top-bar">
            <div class="row column">
                <div class="top-bar-title">
                    <strong class="site_title">Colin</strong>
                </div>
                <div class="top-bar-left">
                    <ul class="menu">
                        <li><input type="search" placeholder="search by material, technique, or product..."></li>
                        <li><button type="button" class="button">Search</button></li>
                    </ul>
                </div>
                <div class="top-bar-right">
                    <ul class="dropdown menu" data-dropdown-menu>
                        <li><a href="/explore">Explore</a></li>
                        <li>|</li>
                        <li><a href="/messages">Messages</a></li>
                        <li>|</li>
                        <li class="has-dropdown">
                            {% if request.user %}
                                <a href="#">
                                    {% if request.user.first_name %}
                                        {{ request.user.first_name }} {{ request.user.last_name|first }}.
                                    {% else %}
                                        {{ request.user.username }}
                                    {% endif %}
                                </a>
                                <ul class="menu vertical">
                                    <li><a href="/profile">Profile</a></li>
                                    <li><a href="/logout">Logout</a></li>
                                </ul>
                            {%  endif %}
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="small-12 large-12 small-centered columns">
                {% block content %} {% endblock %}
            </div>
        </div>
        <script>
            $(document).foundation();
        </script>
    </body>
</html>

colin_dot_com/templates/colin_dot_com/company_list.html
{% extends "colin_dot_com/colin_dot_com.html" %}

{% block navigation %}
    <ul class="breadcrumbs">
      <li><a href="/">home</a></li>
      <li><a class="current" href="/companies">companies</a> </li>
    </ul>
{% endblock %}

{% block content %}
    {% if companies %}
        <table>
        {% for company in companies %}
            <tr>
                <td>{{ company.name }}</td>
                <td>{{ company.date_added }}</td>
                {% if company.blurb %}
                    <td>{{ company.blurb }}</td>
                {%  else %}
                    <td>No description provided.</td>
                {%  endif %}
                <td><a href="./{{ company.id }}">link</a></td>
            </tr>
        {% endfor %}
        </table>
    {% endif %}
{% endblock %}

colin_dot_com/templates/colin_dot_com/list.html
{% extends "colin_dot_com/bauble_dot_com.html" %}

{% block navigation %}
    <ul class="breadcrumbs">
      <li><a href="/">home</a></li>
      <li><a class="current" href="/products">products</a> </li>
    </ul>
{% endblock %}

{% block content %}
    {% if products %}
        <table>
        {% for product in products %}
            <tr>
                <td>{{ product.name }}</td>
                <td>{{ product.pub_date }}</td>
                {% if product.description %}
                    <td>{{ product.description }}</td>
                {%  else %}
                    <td>No description provided.</td>
                {%  endif %}
                <td><a href="./{{ product.id }}">link</a></td>
            </tr>
        {% endfor %}
        </table>
    {% endif %}
{% endblock %}

colin_dot_com/templates/colin_dot_com/show.html
{% extends "colin_dot_com/bauble_dot_com.html" %}

{% block navigation %}
    <ul class="breadcrumbs">
      <li><a href="/">home</a></li>
      <li><a href="/products">products</a> </li>
      <li><a class="current" href="/products/{{ product.id }}">{{ product.name }}</a></li>
    </ul>
{% endblock %}

{% block content %}
    {% if product %}
        <div class="row">
            <div class="small-12 columns">
                <h1>{{ product.name }}</h1>
            </div>
        </div>
        <div class="row">
            <div class="small-12 large-6 columns">
                <img src="{{ MEDIA_URL }}/{{ product.image }}" >
            </div>
            <div class="small-12 large-6 columns">
                <div class="product_description">{{ product.description }}</div>
            </div>
        </div>
        <hr>
        <div class="row">
            <div class="small-6 columns">
                <p> <strong> price </strong> {{ product.price }}</p>
                <p> <strong> size </strong> {{ product.short_size }}</p>
                <p> <strong> color </strong> {{ product.color }}</p>
            </div>
            <div class="small-6 columns">
                <p> <strong> material </strong> {{ product.material }}</p>
                <p> <strong> posted </strong> {{ product.pub_date }}</p>
            </div>
        </div>
    {% endif %}
{% endblock %}

colin_dot_com/templates/colin_dot_com/show_company.html
{% extends "colin_dot_com/colin_dot_com.html" %}

{% block navigation %}
    <ul class="breadcrumbs">
      <li><a href="/">home</a></li>
      <li><a href="/companies">companies</a> </li>
      <li><a class="current" href="/companies/{{ company.id }}">{{ company.name }}</a></li>
    </ul>
{% endblock %}

{% block content %}
    {% if company %}
        <div class="rowset">
            <div class="row">
                <div class="small-12 large-10 columns">
                    <div class="intro">Artin, I'd like you to meet <span class="company_name">{{ company.name }}</span></div>
                </div>
                <!-- {%  if company.logo %}
                    <div class="small-6 large-2 columns">
                        <img src="{{ MEDIA_URL }}/{{ company.logo }}">
                    </div>
                {% endif %} -->
            </div>
            <div class="row">

                <div class="small-6 columns end">
                    <div class="blurb">"{{ company.blurb }}"</div>
                </div>
            </div>
            <div class="row">

                <div class="small-6 large-4 columns">
                    <div class="address"> {{ company.address_line_1 }}<br />{{ company.address_line_2 }}</div>
                </div>
                <div class="small-6 large-4 columns end">
                    <div class="message_me">Message</div>
                </div>
            </div>
        </div>
        <div class="row">
            {% for project in company.project_set.all %}
                <div class="gallery rowset">
                    {% with project.photo_set.all|first as photo %}
                        {% if photo %}
                            <div class="small-6 large-3 columns end">
                                <img src="{{ MEDIA_URL }}/{{ photo.image }}">
                                <!-- <i>{{ project.name }}</i> -->
                            </div>
                        {% endif %}
                    {% endwith %}
                </div>
            {% endfor %}
        </div>
    {% endif %}
{% endblock %}